### ISSUE TITLE
Enum Refactoring

### ISSUE THREAD

**Issue by WhiteHyun** [iOS-PPAK/PPAK_CVS#32]
### 1. 색상 중복

편의점별 색상 코드가 중복되어있습니다.

#### 1-1. UIColor+.swift

https://github.com/iOS-PPAK/PPAK_CVS/blob/63d576c65a9aee9013b1a10de21f9ea48505c0fc/PPAK_CVS/Configuration/Extensions/UIColor%2B.swift#L23-L35

#### 1-2. CVSType.swift

https://github.com/iOS-PPAK/PPAK_CVS/blob/63d576c65a9aee9013b1a10de21f9ea48505c0fc/PPAK_CVS/Configuration/Constants/Enum/CvsType.swift#L46-L67

편의점 별 색상코드는 `UIColor+.swift`대신 `CVSType.swift`에 통합하여 적용하는건 어떤가요? 여러분들은 어떻게 생각하시나요?

### 2. Codable

CVSType과 EventType `Codable`을 준수하도록 변경하고 싶어요. Firebase에서 값을 가져올 때 만들어져있는 Enum을 재사용하는 게 좋을 거 같아서요!

**Comment by isGeekCode** [comment]
1번 의견은 UIColor extension에 있는 컬러값자체를 아예 CVS type에 리턴값으로 잡자는 의견이신가요!!
```swift
case .cu: return UIColor(hex: 0x51485) 
```
이런 방식이요


그리고 CVSType의 컬러가 동일한 이유는 당시 아직 컬러값 extension이 머지가 안된상황이라 넣어둔 임시값입니다

**Comment by isGeekCode** [comment]
그리고 CVSType의 컬러가 동일한 이유는 당시 아직 컬러값 extension이 머지가 안된상황이라 넣어둔 임시값입니다

**Comment by WhiteHyun** [comment]
> 1번 의견은 UIColor extension에 있는 컬러값자체를 아예 CVS type에 리턴값으로 잡자는 의견이신가요!!
> 
> ```swift
> case .cu: return UIColor(hex: 0x51485) 
> ```
> 
> 이런 방식이요

네! `CVSType.cu.backgroundColor`와 같이 접근하는 게 괜찮은 거 같아서요. 기존에도 그렇게 진행하려고 하셨던 것 같은데, 맞으신가요?

**Comment by isGeekCode** [comment]
CVS type수정 #34 으로 이슈를 마무리합니다
