### ISSUE TITLE
PR #23 UIColor extension 관련 추가 의견

### ISSUE THREAD

**Issue by minji0801** [iOS-PPAK/PPAK_CVS#33]
Onboarding 화면에 기본 색상을 적용하다가 closed된 23번 PR(UIColor extension관련)에 개인적인 의견이 생겨 글 올립니다.
지난 pr인데 다시 얘기 꺼낸 점 죄송합니다ㅠ
기본 색상은 아래 사진에 보이듯이 네이비 색상에 가까운 색을 말합니다. (색상 코드 : #030026)

<img width="300" alt="Screen Shot 2022-11-05 at 2 49 46 PM" src="https://user-images.githubusercontent.com/49383370/200304837-fd58eed6-2975-4af1-9410-0e6fc60a195f.png">

▼ 현재 UIColor+.swift의 코드
```swift
import UIKit

extension UIColor {

  convenience init(hex: Int, alpha: CGFloat = 1.0) {
    let components = (
      red: CGFloat((hex >> 16) & 0xff) / 255,
      green: CGFloat((hex >> 08) & 0xff) / 255,
      blue: CGFloat((hex >> 00) & 0xff) / 255
    )
    self.init(red: components.red, green: components.green, blue: components.blue, alpha: alpha)
  }
}

// MARK: - Store's SymbolColor
extension UIColor {

  static let cuBackGroundColor = UIColor(hex: 0x51485)
  static let cuFontColor = UIColor(hex: 0x9DC92A)
  static let gsBackGroundColor = UIColor(hex: 0x63514D)
  static let gsFontColor = UIColor(hex: 0x00D7F1)
  static let seBackGroundColor = UIColor(hex: 0xFF8329)
  static let seFontColor = UIColor(hex: 0x005B45)
  static let msBackGroundColor = UIColor(hex: 0x003893)
  static let msFontColor = UIColor(hex: 0xF0F0F0)
  static let emBackGroundColor = UIColor(hex: 0x56555B)
  static let emFontColor = UIColor(hex: 0xFFB41D)
}
```

- 의견 1) 
  기본 색상도 추가해주세요.  기본 색상은 첨부한 첫 번째 사진에 보이듯이 네이비 색상에 가까운 색을 말합니다. (색상 코드 : #030026)
- 의견 2)  
  편의점 이름을 풀네임으로 적어주시면 감사하겠습니다. (se -> sevenEleven, ms -> miniStop, em -> emart)
- 의견 3) 
  hex 값은 String으로 받는게 맞다고 생각합니다. 이건 제가 23번 pr을 제대로 확인하지 않았던 것 같습니다. 그때 말씀드렸어야 했는데 죄송합니다ㅠ Figma 상에 색상표가 아래 사진 처럼 나와있고 혹여나 나중에 색상이 변경될 시 이 색상표를 토대로 코드도 변경해야할 텐데 바로 String 값을 넣어서 처리하는 게 좋을 것 같아요!
  <img width="300" alt="Screen Shot 2022-11-05 at 2 47 16 PM" src="https://user-images.githubusercontent.com/49383370/200305302-3c782c9b-1f52-472d-a56a-9673e6c47e3b.png">

**Comment by isGeekCode** [comment]
#34 CVS Type 수정으로 이슈를 마무리합니다!
